{% set name = "argp-standalone" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://www.lysator.liu.se/~nisse/misc/{{ name }}-{{ version }}.tar.gz
    sha256: dec79694da1319acd2238ce95df57f3680fea2482096e483323fddf3d818d8be
    patches:
      - win.patch     # [win]
      - unistd.patch  # [win]

build:
  number: 1
  skip: true  # [linux and osx]
  run_exports:
    - {{ pin_subpackage("argp-standalone", max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - make         # [unix]
    - m2-autoconf  # [win]
    - m2-automake1.15  # [win]
    - m2-libtool   # [win]
    - m2-make      # [win]
    - m2-grep      # [win]

test:
  commands:
    # - test -f ${PREFIX}/lib/libargp.a
    # - test -f ${PREFIX}/include/argp.h

about:
    home: https://www.lysator.liu.se/~nisse/misc
    license: LGPL-2.0-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: Standalone version of arguments parsing functions from GLIBC.

extra:
  recipe-maintainers:
    - davidbrochart
    - wolfv
