{% set name = "argp-standalone" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/argp-standalone/argp-standalone/archive/refs/tags/{{ version }}.tar.gz
    sha256: c29eae929dfebd575c38174f2c8c315766092cec99a8f987569d0cad3c6d64f6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("argp-standalone", max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja

test:
  commands:
    - test -f ${PREFIX}/lib/libargp.a  # [unix]
    - test -f ${PREFIX}/include/argp.h  # [unix]

about:
    home: https://www.lysator.liu.se/~nisse/misc
    license: LGPL-2.0-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: Standalone version of arguments parsing functions from GLIBC.

extra:
  recipe-maintainers:
    - davidbrochart
    - wolfv
